---

- name: "Add additional apt keys"
  when:
    - "item.key is defined"
    - "item.key"
    - "item.key.id is defined and item.key.id or item.key.url is defined and item.key.url"
  apt_key:
    id: "{{ item.key.id | default(omit) }}"
    url: "{{ item.key.url | default(omit) }}"
    keyserver: "{{ item.key.keyserver | default(omit) }}"
    validate_certs: "{{ item.key.validate_certs | default(omit) }}"
    state: "present"
  loop: "{{ erlang_repo_list | flatten(levels=1) }}"

- name: "Ensure accessing metadata and packages available over https is possible"
  apt:
    name: "{{ item }}"
    state: "present"
  loop:
    - "apt-transport-https"
    - "ca-certificates"

- name: "Add additional apt repositories"
  when:
    - "item.repo is defined"
    - "item.repo"
  apt_repository:
    repo: "{{ item.repo }}"
    state: "present"
  loop: "{{ erlang_repo_list | flatten(levels=1) }}"

- name: "Install packages"
  apt:
    name: "{{ (item is mapping) | ternary(item['pkg'], item) }}"
    update_cache: "{{ erlang_update_cache | default(omit) }}"
    cache_valid_time: "{{ erlang_cache_valid_time | default(omit) }}"
    state: "present"
    default_release: "{{ item['release'] | default(omit) }}"
  loop: "{{ erlang_package_list | flatten(levels=1) }}"
